Homework 00 - Optinal

In [2]:
import pandas as pd
import numpy as np

In [3]:
# CONSTANTS
DATA_PATH = "interactive_data.csv"

In [4]:
df = pd.read_csv(DATA_PATH) # this reads the file, this is for CSV, but can also use A VOIR

In [8]:
df.head() #df displays the table (no brackets). df.head(x) only the first x rows (if nothing as x then 5). df.tail() last five

,Unnamed: 0,Intent,Gender,Age,Race,Deaths,Population,Rate
0,1,None selected,None selected,None selected,None selected,33599,316299978,10.6
1,2,None selected,None selected,None selected,White,22079,197369634,11.2
2,3,None selected,None selected,None selected,Black,7765,38896382,20.0
3,4,None selected,None selected,None selected,Hispanic,3007,54049078,5.6
4,5,None selected,None selected,None selected,Asian/Pacific Islander,442,16315561,2.7

In [10]:
df.shape #gives the shape of what we loaded (rows,columns). df.shape[0] Gives number of rows, and df.shape[1] columns

(540, 8)

In [11]:
df.columns #prints the names of the columns

Index(['Unnamed: 0', 'Intent', 'Gender', 'Age', 'Race', 'Deaths', 'Population',
       'Rate'],
      dtype='str')

In [15]:
df.describe() #givs info like count, mean etc...

C:\Users\marwa\anaconda3\envs\ada\Lib\site-packages\pandas\core\nanops.py:1028: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)

       Unnamed: 0        Deaths    Population    Rate
count  540.000000    540.000000  5.400000e+02  468.00
mean   270.500000    995.518519  2.342963e+07     inf
std    156.028843   3322.544944  4.501642e+07     NaN
min      1.000000      0.000000  0.000000e+00    0.00
25%    135.750000      1.000000  1.428743e+06    0.10
50%    270.500000     22.000000  6.856696e+06    0.45
75%    405.250000    191.750000  2.490155e+07    3.40
max    540.000000  33599.000000  3.163000e+08     inf

In [17]:
#to access one column
df["Race"] #this returns the entire, column, including duplicates

0               None selected
1                       White
2                       Black
3                    Hispanic
4      Asian/Pacific Islander
                ...
535                     White
536                     Black
537                  Hispanic
538    Asian/Pacific Islander
539                     Other
Name: Race, Length: 540, dtype: str

In [18]:
df["Race"].value_counts() #gives how many times each value in the race column appears.

Race
None selected             90
White                     90
Black                     90
Hispanic                  90
Asian/Pacific Islander    90
Other                     90
Name: count, dtype: int64

In [23]:
# to count for only one, we can do this:
(df["Race"] == "White").sum()
#this works because the == creates the column but with true, false etc... in column, and so summing false = 0, true =1, so it works

np.int64(90)

In [27]:
white_deaths = df[df["Race"] == "White"]
white_deaths.head()
#this works becaue the intside [] gives the filtered true false etc... and so the df[something] will only keep the trues.

,Unnamed: 0,Intent,Gender,Age,Race,Deaths,Population,Rate
1,2,None selected,None selected,None selected,White,22079,197369634,11.2
7,8,None selected,None selected,Under 15,White,242,31538832,0.8
13,14,None selected,None selected,15 - 34,White,5244,48773131,10.8
19,20,None selected,None selected,35 - 64,White,11396,81870182,13.9
25,26,None selected,None selected,65+,White,5192,35187489,14.8

In [31]:
#for counting rows that satisfy a condition
(df["Intent"] == "Suicide").sum()
# can also instead of sum use mean, median, min, max, std,

np.int64(108)

In [34]:
#to filter and keep rows with nothindf or keep only rows with something in
df[df["Intent"].isna()]

Empty DataFrame
Columns: [Unnamed: 0, Intent, Gender, Age, Race, Deaths, Population, Rate]
Index: []

In [38]:
df.shape

(540, 8)

In [39]:
df.dropna().shape #this gets rids of all the empty rows. REMOVES ALL ROWS WITH AT LEAST ONE MISSING VALUE

(468, 8)

In [47]:
df.dropna(subset=["Rate"]) #drops all rows where only one column in missing. In this case only rate has Nan because of 0 deaths so cant divide.

,Unnamed: 0,Intent,Gender,Age,Race,Deaths,Population,Rate
0,1,None selected,None selected,None selected,None selected,33599,316299978,10.6
1,2,None selected,None selected,None selected,White,22079,197369634,11.2
2,3,None selected,None selected,None selected,Black,7765,38896382,20.0
3,4,None selected,None selected,None selected,Hispanic,3007,54049078,5.6
4,5,None selected,None selected,None selected,Asian/Pacific Islander,442,16315561,2.7
...,...,...,...,...,...,...,...,...
529,530,Unknown,Male,65+,White,23,15608050,0.1
530,531,Unknown,Male,65+,Black,2,1520192,0.1
531,532,Unknown,Male,65+,Hispanic,0,1419828,0.0
532,533,Unknown,Male,65+,Asian/Pacific Islander,0,750151,0.0
533,534,Unknown,Male,65+,Other,0,255719,0.0

In [48]:
# to sort per one column ascending or descending
df.sort_values("Rate", ascending=False)

,Unnamed: 0,Intent,Gender,Age,Race,Deaths,Population,Rate
319,320,Homicide,Male,5,White,2,0,inf
318,319,Homicide,Male,5,None selected,3,0,inf
30,31,None selected,None selected,5,None selected,6,0,inf
31,32,None selected,None selected,5,White,4,0,inf
174,175,Suicide,Female,5,None selected,1,0,inf
...,...,...,...,...,...,...,...,...
535,536,Unknown,Male,5,White,0,0,NaN
536,537,Unknown,Male,5,Black,0,0,NaN
537,538,Unknown,Male,5,Hispanic,0,0,NaN
538,539,Unknown,Male,5,Asian/Pacific Islander,0,0,NaN
539,540,Unknown,Male,5,Other,0,0,NaN

In [50]:
# to select multiple columns and keep only those columns in the order that is writtenS
df[["Rate", "Gender", "Age"]]

     Rate         Gender            Age
0    10.6  None selected  None selected
1    11.2  None selected  None selected
2    20.0  None selected  None selected
3     5.6  None selected  None selected
4     2.7  None selected  None selected
..    ...            ...            ...
535   NaN           Male              5
536   NaN           Male              5
537   NaN           Male              5
538   NaN           Male              5
539   NaN           Male              5

[540 rows x 3 columns]

In [52]:
# to display in one cell different things, otherwise only the last expression is shown
display(df.head())
display(df.info())
display(df["Rate"].value_counts())

,Unnamed: 0,Intent,Gender,Age,Race,Deaths,Population,Rate
0,1,None selected,None selected,None selected,None selected,33599,316299978,10.6
1,2,None selected,None selected,None selected,White,22079,197369634,11.2
2,3,None selected,None selected,None selected,Black,7765,38896382,20.0
3,4,None selected,None selected,None selected,Hispanic,3007,54049078,5.6
4,5,None selected,None selected,None selected,Asian/Pacific Islander,442,16315561,2.7

<class 'pandas.DataFrame'>
RangeIndex: 540 entries, 0 to 539
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  540 non-null    int64
 1   Intent      540 non-null    str
 2   Gender      540 non-null    str
 3   Age         540 non-null    str
 4   Race        540 non-null    str
 5   Deaths      540 non-null    int64
 6   Population  540 non-null    int64
 7   Rate        468 non-null    float64
dtypes: float64(1), int64(3), str(4)
memory usage: 33.9 KB

None

Rate
0.0     93
0.1     69
0.2     29
0.3     22
0.4     21
        ..
73.5     1
12.4     1
5.0      1
21.0     1
4.9      1
Name: count, Length: 112, dtype: int64

In [54]:
###########################
## START OF THE HOMEWORK ##
###########################

- Nearly *two-thirds* of gun deaths are *suicides*.
- More than *85 percent* of suicide victims are *male*.
- Around *a third* of all gun deaths are *homicides*.
- Around *two-thirds* of homicide victims who are *males* in the *age-group of 15--34* are *black*.
- *Women* constitue only *15 percent* of the total *homicide* victims.
These are the claims we want to show from this dataset

In [57]:
df = pd.read_csv(DATA_PATH)
df.head()

,Unnamed: 0,Intent,Gender,Age,Race,Deaths,Population,Rate
0,1,None selected,None selected,None selected,None selected,33599,316299978,10.6
1,2,None selected,None selected,None selected,White,22079,197369634,11.2
2,3,None selected,None selected,None selected,Black,7765,38896382,20.0
3,4,None selected,None selected,None selected,Hispanic,3007,54049078,5.6
4,5,None selected,None selected,None selected,Asian/Pacific Islander,442,16315561,2.7

In [77]:
# 2/3 of gun deaths are suicide
number_of_suicides = df[(df["Intent"] == "Suicide")&(df["Gender"] == "None selected")&(df["Race"] == "None selected")&(df["Age"] == "None selected")]["Deaths"].iloc[0]
# This means zake dataset filter for rows wherw Intent ==..., Gender....., then take th deaths column, and give the ifrst value

total_deaths = df[(df["Intent"] == "None selected")&(df["Gender"] == "None selected")&(df["Race"] == "None selected")&(df["Age"] == "None selected")]["Deaths"].iloc[0]

fraction_of_suicides = number_of_suicides / total_deaths *100

print(number_of_suicides)
print(total_deaths)
print("The total percentage of suicides is %d percent." %(fraction_of_suicides))

21058
33599
The total percentage of suicides is 62 percent.

In [80]:
#More than 85 percent of suicide victims are male.
male_suicides = df[(df["Intent"] == "Suicide")&(df["Gender"] == "Male")&(df["Race"] == "None selected")&(df["Age"] == "None selected")]["Deaths"].iloc[0]

fraction_of_male_sc = male_suicides / number_of_suicides * 100
print("The total percentage of male suicides is %d percent." %(fraction_of_male_sc))

The total percentage of male suicides is 86 percent.

In [84]:
# Around a third of all gun deaths are homicides.
number_of_h = df[(df["Intent"] == "Homicide")&(df["Gender"] == "None selected")&(df["Race"] == "None selected")&(df["Age"] == "None selected")]["Deaths"].iloc[0]
# This means zake dataset filter for rows wherw Intent ==..., Gender....., then take th deaths column, and give the ifrst value

total_deaths = df[(df["Intent"] == "None selected")&(df["Gender"] == "None selected")&(df["Race"] == "None selected")&(df["Age"] == "None selected")]["Deaths"].iloc[0]

fraction_of_h = number_of_h / total_deaths *100

print(number_of_suicides)
print(total_deaths)
print("The total percentage of homice is %d percent." %(fraction_of_h))

21058
33599
The total percentage of homice is 34 percent.

In [87]:
#Around two-thirds of homicide victims who are males in the age-group of 15--34 are black.
number_of_h_m_15_34_b = df[(df["Intent"] == "Homicide")&(df["Gender"] == "Male")&(df["Race"] == "Black")&(df["Age"] < "34")&(df["Age"] > "15")]["Deaths"].iloc[0]
number_of_h_m_15_34 = df[(df["Intent"] == "Homicide")&(df["Gender"] == "Male")&(df["Race"] == "None selected")&(df["Age"] < "34")&(df["Age"] > "15")]["Deaths"].iloc[0]

# WHEN FILTERING BY NUMBER FROM CSV MIGHT NEED TO PUT THE FILTERING BETWEEN ".."

Fraction = number_of_h_m_15_34_b/number_of_h_m_15_34*100
print(Fraction)

66.13496932515336

In [88]:
#*Women* constitue only *15 percent* of the total *homicide* victims.
number_of_h_w = df[(df["Intent"] == "Homicide")&(df["Gender"] == "Female")&(df["Race"] == "None selected")&(df["Age"] == "None selected")]["Deaths"].iloc[0]



fraction = number_of_h_w / number_of_h * 100
print(fraction)

15.273750639604296